### ISSUE TITLE
Can't install versions higher then 2.1 using composer

### ISSUE THREAD

**Issue by hostep** [ericthehacker/magento2-configscopehints#9]
Hi

When following the installation instructions, I only get version 2.1 and not the latest version.
Also when explicitly asking for version 3.1.0 composer can't find this version.
I believe this is because of the hardcoded version `2.1` which is included in the `composer.json` file. I think you'll best remove it and then composer will fetch the versions from the tags.

This is the what composer sees over here (after clearing my composer cache to be absolutely sure it isn't a local problem):
```
$ composer show --all ericthehacker/magento2-configscopehints
...
versions : dev-master, 2.1, 2.0, dev-feature/dynamic-paths-support
...
```

----

Also: version 3.x isn't compatible with Magento 2.0.x I think? (not actually tested). Then shouldn't the module specify version constraints in the `composer.json` file so version 3.x can't be installed on Magento 2.0.x ?
Since this module has a direct dependency on the Config module, you could add a constraint like:
```json
"magento/module-config": "^100.1"
```
See: [Magento 2.0.11](https://github.com/magento/magento2/blob/2.0.11/app/code/Magento/Config/composer.json) vs [Magento 2.1.0](https://github.com/magento/magento2/blob/2.1.0/app/code/Magento/Config/composer.json)

So composer automatically finds the correct version of this module to install if you don't explicitly specify a version. People would then get version 2.x of this module when they have Magento 2.0.x and get version 3.x when they have Magento 2.1.x

But unfortunately it is too late now I think, since version 3.0.0 and 3.1.0 don't have this constraint in there.

Not sure if all of the above is 100% correct, this is just in theory, not really tested.

**Comment by ericthehacker** [comment]
@hostep 
I think you're correct, and I've updated the version in the composer.json file, which appears to fix the issue.

Based on the approach I took, I *think* that 3.x of the module is actually still compatible with Magento 2.0.x. However, I'll keep in mind the dependency version requirements for future releases to try to make this as smooth for integrators as possible.

Thanks for well thought out suggestions. :)

**Comment by hostep** [comment]
Thanks @ericthehacker!

Although, I think it is best practice to remove the version from the `composer.json` file, otherwise you have to think about it everytime you tag a new version.
I'm pretty sure composer picks up the versions from the tags if there is no explicit version defined in the `composer.json` file.
See: https://getcomposer.org/doc/04-schema.md#version
